name: chefchat
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi[standard]
    - uvicorn
    - pymupdf
    - langchain
    - langchain-community
    - chromadb
    - sentence-transformers
    - python-multipart
    - ollama